
server:
  port: 10012
# ˝æ›ø‚≈‰÷√
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.96.66:3306/trip?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: LoginProvider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#mybatis:
#  mapper-locations: